### ISSUE TITLE
problem: Stock Status updatable by people not near supermarket

### ISSUE THREAD

**Issue by tel77** [howlongistheline/howlongistheline.org#178] opened 2020-04-20 02:39 UTC
Today I tested the Stock Status feature by submitting "Test" as the product (twice), and it was accepted, even though I am maybe 10km from the supermarket (Pak'nSave Lower Hutt).  It also allowed me to put "." (period) & " " (space) as the product.  If they haven't been removed, you should be able to see these here:
  https://howlongistheline.org/stocks?id=Z6egNsr2PjJMhuiWJ

Is the system meant to ensure stock is only updated from devices near the store, as I think it does for queue length updates?

Some side issues (which I can open separately if you see merit in them):
Should it accept duplicate entries of the same product (e.g. "Test"), and products like "." & " "?

I'm not saying any of these are necessarily wrong, but I expect at least some of them would be and I'm raising the questions.

Thanks for your efforts and keep up the good work!

**Comment by gazhayes** [comment] 2020-04-20 03:10
This isn't a problem right now because people aren't really using the stock status feature anyway. If it starts becoming an aspect that is used and fake out-of-stock items become a problem then it will definitely be worth solving.

**Comment by tel77** [comment] 2020-04-20 04:13
Thanks for your prompt response, Gareth.

Well when I search for "Lower Hutt", and click "Stock Status" on each of the supermarkets it finds, I can see most of them show items which have run out, and most of *those* supermarkets listed "Flour" and "Cocoa" 18 hours ago, so I'm not sure if that's legit or not.  This includes the Pak'nSave Lower Hutt supermarket that I linked to originally.

What area or whatever are you seeing Stock Status NOT being used, Gareth?

**Comment by jimkleine** [comment] 2020-04-20 07:30
@tel77 Welcome to GitHub.  I have just removed your "test data".  I will add a screenshot to this Issue, however I would prefer that you didn't use the production database for testing.  You are, however, more than welcome to fork this project and contribute a fix.  That will give you a local database copy to test with :-)

@gazhayes There are currently ~235 stores with at least one out-of-stock.  I sampled a handful of them and they mostly seem to be being used responsibly.  There **is** an issue with duplicate products e.g. Milk, although it is valid to update the date/time an out-of-stock was last observed.

@ioioio8888 I think this may have originally been one of your contributions.  Do you have time to look at this?

**Comment by jimkleine** [comment] 2020-04-20 07:39
This was how @tel77's additions were presenting before I removed them from the database:

![Missing OutOfStock Validation](https://user-images.githubusercontent.com/47098744/79725600-8f618c80-833d-11ea-8e79-285b8b312e45.jpg)

possible solution(s):

1.  Perform locality check before allowing updates;

2.  Exclude items below a minimum string length (this will likely have to be short e.g. "< 3" i.e. "Ice", "Milk"); and

3.  If the product already exists, only update "time" (which is a DateTime field).  This will still gradually accumulate typos to product names.

**Comment by gazhayes** [comment] 2020-04-20 10:28
> There is an issue with duplicate products e.g. Milk, although it is valid to update the date/time an out-of-stock was last observed.

Simplest solution to this would be to set a unique index on the text of the item and just update the time in the case of duplicates. Though I wonder if that really is a problem, maybe the history is also relevant.

Just based on my own behaviour, I can't be bothered to update the stock status while I'm at the store and I just want to get my stuff and get out. But I do update it when I get home. Whereas this isn't a problem when you're waiting in line with not much else to do anyway. That's why I think it's better to be really sure that the system is being abused somehow before restricting this to location.

**Comment by tel77** [comment] 2020-04-21 00:43
Thanks for all your responses.

BTW, how are stock levels meant to be updated so products no longer show as being out-of-stock?  Do they disappear off the list after X days, or can people somehow update them?  And where is this documented?  I can't see any way on the site and I don't see it in the FAQ.

@jimkleine 
> "...but I would prefer that you didn't use the production database for testing. You are, however, more than welcome to fork this project and contribute a fix. That will give you a local database copy to test with :-)"
If I wanted to invest the time to learn a new language that I might not use again, and understand the existing relevant code, and learn how to set up an appropriate local environment, and got approval to make such changes (which it seems may not be wanted at all), then that might be practical, but none of those apply so it isn't.  I didn't expect my data to be accepted by the system, especially because I wasn't at the shop, which is a requirement for changing the queue length.  Considering the number of potential users of this system, including those outside of NZ, some whom might just want to put obscenities, etc in your data (**without** telling you about it), your request for the likes of me (who told you about my tests) not to do it, might be the least of your problems if this site is used for much longer.  (Maybe it won't need to be used for much longer.)  I had no other **practical** way to test it.  I'm hardly going to spend hours or days trying to work out how to set up a test environment to just see if the site has catered for a few cases.  Who would, apart from someone who's decided to get heavily involved?

**Comment by gazhayes** [comment] 2020-04-21 00:51
@tel77 
> Do they disappear off the list after X days, or can people somehow update them?

No but that's a good idea, might just hide them after 2 days or something.

**Comment by tel77** [comment] 2020-04-21 01:03
Sometimes getting rid of them after X days might work, but there will be no value of X which will be appropriate for all cases, because some items could be replenished within minutes of being reported as being out-of-stock, and some could take a week.

Currently, do they just accumulate forever, with no way for anyone to clear them when they're noticed as being in-stock again?

**Comment by gazhayes** [comment] 2020-04-21 09:36
> Currently, do they just accumulate forever, with no way for anyone to clear them when they're noticed as being in-stock again?

Yeah that's right.

So actually the problem here might simply be that people can't mark them as being in stock again. 

> and got approval to make such changes (which it seems may not be wanted at all)

I understand your other reasons, but I'd like to point out that the contribution protocol here means this particular objection is not a problem. If you follow the contribution protocol, your change gets merged and pushed into production. There's no one deciding if it's the right "direction" for the project to go in etc.

**Comment by gazhayes** [comment] 2020-04-21 09:41
Added #187 which is related

**Comment by jimkleine** [comment] 2020-04-21 15:45
@tel77 This seems to be an issue you are quite passionate about.

> If I wanted to invest the time to learn a new language that I might not use again, and understand the existing relevant code, and learn how to set up an appropriate local environment, and got approval to make such changes (which it seems may not be wanted at all), then that might be practical, but none of those apply so it isn't. ... I'm hardly going to spend hours or days trying to work out how to set up a test environment to just see if the site has catered for a few cases. Who would, apart from someone who's decided to get heavily involved?

Not all of the team of **volunteers** working on this project typically works with the Meteor stack either, but we each made a personal choice that the benefit to others outweighed any inconvenience to ourselves.

>  I didn't expect my data to be accepted by the system, especially because I wasn't at the shop, which is a requirement for changing the queue length ... I had no other practical way to test it.

It is better to ask for permission than forgiveness.  The difference between grafitti and a mural is that one artist had permission.  One of us would likely have been prepared to either help you set up a development environment or make a test database available to you if you had asked first.

> Considering the number of potential users of this system, including those outside of NZ, some whom might just want to put obscenities, etc in your data (without telling you about it), your request for the likes of me (who told you about my tests) not to do it, might be the least of your problems if this site is used for much longer.

Most of our users seem pretty well behaved so far, and we have been focused on adding useful features.  Your access wasn't the result of using the system as intended (I'm referring to PAK'nSAVE not selling cartons of "Test") and finding a bug; it was more in the nature of penetration testing, [which is fraught, even for professionals](https://www.zdnet.com/article/charges-dropped-against-penetration-testers-who-broke-into-courthouse/).

Regardless, we have taken your feedback on board and I can see that changes are already being made to the out-of-stock functionality.

**Comment by jimkleine** [comment] 2020-04-22 13:56
@tel77 I'll investigate creating a test environment for you.  I'm just not quite sure when I will get to it.

**Comment by tel77** [comment] 2020-04-22 22:55
Thanks for the offer of creating a test environment for me, Jim.  I don't know whether I'll be doing any more testing, but it may be useful for others, and maybe it can be linked to from the FAQ or similar.

Meanwhile, regarding my fraud (which I committed then brought to your attention), I've cuffed myself to a fixed object and am awaiting authorities to pick me up...after lockdown, when it will be safe to approach me.  Not sure if it really is fraud if the site doesn't specify what people are and are not allowed to do, but I'll find out in court I guess.  One point which may be in my favour is, I doubt that site visitors (briefly) seeing "Test", etc, in the list of out-of-stock items would be mislead by that.

**Comment by jimkleine** [comment] 2020-04-23 06:14
> Thanks for the offer of creating a test environment for me, Jim. I don't know whether I'll be doing any more testing, but it may be useful for others, and maybe it can be linked to from the FAQ or similar.

@tel77 If you had stopped there, you would have been fine.

> Meanwhile, regarding my fraud ...

Unfortunately, [fraught is an actual word](https://www.lexico.com/definition/fraught), and it doesn't mean what you apparently think it means.

**Comment by jimkleine** [comment] 2020-04-23 06:21
@gazhayes I think we have covered the basics with recent pull requests (#188, #189), so I'm going to close this issue for now.

If we need more in the future, I'll consider adding a banned words list to the database (I don't want to put those directly in the source, for obvious reasons).

**Closed by jimkleine** 2020-04-23 06:21 UTC

**Comment by tel77** [comment] 2020-04-23 21:14
Sorry Jim, I thought you meant "fraud" when you wrote "fraught".
